### ISSUE TITLE
Match to bool

### ISSUE THREAD

**Issue by eberkund** [oriser/regroup#5]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was a way store whether there was a match into a boolean.

**Describe the solution you'd like**
I was thinking there could be an additional struct tag to configure this but I am not sure what it should look like. Booleans are currently supported but only to match true or false.

```go
type B struct {
	HasSuffixFoo bool `regroup:"foo,flag"`
}

var re = regroup.MustCompile(`.*(?P<foo>foo)?`)
```

**Describe alternatives you've considered**
Currently I just check the value of the struct after matching.

**Comment by oriser** [comment]
Hi @eberkund!
Thank you for the suggestion :)
In case no match was found, an error will be returned. The type of the error will be `NoMatchFoundError`
So, you can verify a match that way.

Is that satisfy your requirement?

**Comment by eberkund** [comment]
Let me try to do a better job at explaining. The use case here is for when you have an optional part of the pattern.

Imagine some inputs like this:

```
username=bob,email=bob@example.com
username=alice,email=alice@example.com,admin
```

and a corresponding Go struct like this:
```go
type User struct {
    Username string
    Email string
    IsAdmin bool
}
```

My understanding is that there isn't really a nice way to handle this with regroup so I suggested having a "flag" option which would be true if that optional match group is present and false if it is not.

This is different from an input string that looks some like this (which is supported by the current features):

```
username=bob,email=bob@example.com,admin=false
username=alice,email=alice@example.com,admin=true
```

**Comment by oriser** [comment]
Ah I understand. You want to mark a field as a flag, so that the existence of the group alone will mark it as true.
That sound like a great addition. Would you like the contribute this feature?

**Comment by eberkund** [comment]
> Ah I understand. You want to mark a field as a flag, so that the existence of the group alone will mark it as true. That sound like a great addition. Would you like the contribute this feature?

Exactly, yeah I would not mind contributing. I will take a look when I have some time.
